# Generated by Django 4.2 on 2026-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('reviewing', 'Reviewing'), ('draft', 'Draft'), ('approval', 'Approval'), ('approved', 'Approved'), ('locked', 'Locked')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
    ]
