# Generated by Django 6.0.3 on 2026-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('started', 'Started'), ('draft', 'Draft'), ('approval', 'Approval'), ('approved', 'Approved'), ('locked', 'Locked')], default='created', max_length=20),
        ),
    ]
